### ISSUE TITLE
Significance of tests not visible in view(seas())

### ISSUE THREAD

**Issue by andrbachm** [christophsax/seasonalview#14]
The significance of the tests (e.g. test for no seasonality in final series) is sometimes not visible in the shiny interface. For example, summary(seas(x)) shows that H0 is rejected on the 1% level while in view() 1% is written in white color on a white ground, hence it is not visible. 
Most likely, the problem is that the box around the "1%" has is of white color as well.

**Comment by christophsax** [comment]
@felicitaskemeny FYI

**Comment by christophsax** [comment]
Reprex:

``` r
library(seasonal)
summary(seas(fdeaths))
#> 
#> Call:
#> seas(x = fdeaths)
#> 
#> Coefficients:
#>                 Estimate Std. Error z value Pr(>|z|)    
#> Constant       -0.015780   0.007328  -2.153   0.0313 *  
#> AO1976.Feb      0.433445   0.092176   4.702 2.57e-06 ***
#> MA-Seasonal-12  0.631191   0.106224   5.942 2.81e-09 ***
#> ---
#> Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
#> 
#> SEATS adj.  ARIMA: (0 0 0)(0 1 1)  Obs.: 72  Transform: log
#> AICc: 660.9, BIC: 668.5  QS (no seasonality in final):    0  
#> Box-Ljung (no autocorr.): 24.23   Shapiro (normality): 0.9763
```

`constant` is significant on the 5% level, but the HTML GUI shows this white on white...
```r
library(sesonalview)
view(seas(fdeaths))
```

<img width="332" alt="image" src="https://user-images.githubusercontent.com/1390827/184475318-2ec8b5b5-d2fb-461c-aedf-7f77b3c60f06.png">

**Comment by christophsax** [comment]
Now, as expected:

<img width="262" alt="image" src="https://user-images.githubusercontent.com/1390827/184475700-358a6c74-2d21-48ae-9530-55d39294e144.png">

**Comment by christophsax** [comment]
The high-significant tags here were invisible too, as mentioned by @andrbachm. Fixed too:

<img width="315" alt="image" src="https://user-images.githubusercontent.com/1390827/184476047-5e2a1192-7a6b-49f4-a291-9811bb8d3470.png">
